# Generated by Django 4.0.2 on 2022-02-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_fichier_a_mordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='Fichier_a_mordre',
            field=models.FileField(upload_to='chem'),
        ),
    ]
