# Generated by Django 4.0.2 on 2022-03-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='planning',
            field=models.FileField(default='', upload_to='books/planning/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='books/html/'),
        ),
    ]
