# Generated by Django 4.0.2 on 2022-03-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_book_planning_alter_book_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Band',
        ),
    ]
