# Generated by Django 4.0.2 on 2022-03-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_delete_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anniversaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='books/html/')),
                ('planning', models.FileField(upload_to='books/planning/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
