# Generated by Django 4.0.2 on 2022-03-04 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_anniversaire_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anniversaire',
            name='planning',
        ),
        migrations.RemoveField(
            model_name='anniversaire',
            name='title',
        ),
    ]
